# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-29 14:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChildProfile',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('case_no', models.CharField(max_length=10)),
                ('hospital_name', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=5)),
                ('date_of_birth', models.DateField()),
                ('age', models.IntegerField()),
                ('mother_tongue', models.CharField(max_length=10)),
                ('father_name', models.CharField(max_length=20)),
                ('mother_name', models.CharField(max_length=20)),
                ('contact_no', models.BigIntegerField()),
                ('disease', models.CharField(max_length=50)),
                ('critical', models.BooleanField(default=False)),
                ('wish_type', models.CharField(max_length=20)),
                ('wish1', models.CharField(max_length=20)),
                ('wish2', models.CharField(max_length=20)),
                ('wish3', models.CharField(max_length=20)),
                ('date_submitted', models.DateField()),
                ('approved_wish', models.CharField(max_length=20)),
                ('wish_status', models.IntegerField(default=1)),
                ('family', models.TextField(max_length=500)),
                ('friend', models.TextField(max_length=500)),
                ('color', models.TextField(max_length=500)),
                ('book', models.TextField(max_length=500)),
                ('game', models.TextField(max_length=500)),
                ('food', models.TextField(max_length=500)),
                ('music_movie', models.TextField(max_length=500)),
                ('hobby', models.TextField(max_length=500)),
                ('cartoon', models.TextField(max_length=500)),
                ('actor', models.TextField(max_length=500)),
                ('trip', models.TextField(max_length=500)),
                ('ambition', models.TextField(max_length=500)),
                ('bigwish1', models.TextField(max_length=500)),
                ('bigwish2', models.TextField(max_length=500)),
                ('bigwish3', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doc_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('hospital', models.CharField(max_length=20)),
                ('contact_no', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('donor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('contact_no', models.BigIntegerField()),
                ('points', models.IntegerField()),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('method_of_payment', models.CharField(max_length=50)),
                ('date_of_pay', models.DateField(default=datetime.date.today)),
                ('child_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MakeAWish.ChildProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('govt_id_no', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=10)),
                ('id_type', models.CharField(max_length=20)),
                ('volunteer_type', models.CharField(max_length=20)),
                ('hospital', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=False)),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='childprofile',
            name='doctor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MakeAWish.Doctor'),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='donor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MakeAWish.Donor'),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='vol_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MakeAWish.Volunteer'),
        ),
    ]
