# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-30 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MakeAWish', '0002_auto_20170729_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('contact_no', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=10)),
                ('area', models.CharField(max_length=20)),
            ],
        ),
    ]
