# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngo',
            name='location',
        ),
        migrations.RemoveField(
            model_name='ngo',
            name='timings',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='timiings',
        ),
        migrations.AddField(
            model_name='ngo',
            name='lat',
            field=models.DecimalField(decimal_places=10, default=None, max_digits=15),
        ),
        migrations.AddField(
            model_name='ngo',
            name='long',
            field=models.DecimalField(decimal_places=10, default=None, max_digits=15),
        ),
        migrations.AddField(
            model_name='ngo',
            name='pref1',
            field=models.IntegerField(choices=[(0, 'Morning'), (1, 'Afternoon'), (2, 'Evening')], default=None),
        ),
        migrations.AddField(
            model_name='ngo',
            name='pref2',
            field=models.IntegerField(choices=[(0, 'Morning'), (1, 'Afternoon'), (2, 'Evening')], default=None),
        ),
        migrations.AddField(
            model_name='ngo',
            name='pref3',
            field=models.IntegerField(choices=[(0, 'Morning'), (1, 'Afternoon'), (2, 'Evening')], default=None),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lat',
            field=models.DecimalField(decimal_places=10, default=None, max_digits=15),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='long',
            field=models.DecimalField(decimal_places=10, default=None, max_digits=15),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pref1',
            field=models.IntegerField(choices=[(0, 'Morning'), (1, 'Afternoon'), (2, 'Evening')], default=None),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pref2',
            field=models.IntegerField(choices=[(0, 'Morning'), (1, 'Afternoon'), (2, 'Evening')], default=None),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pref3',
            field=models.IntegerField(choices=[(0, 'Morning'), (1, 'Afternoon'), (2, 'Evening')], default=None),
        ),
        migrations.DeleteModel(
            name='Timing',
        ),
    ]
