# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 14:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0002_auto_20161104_0815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
    ]
