# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0004_needy_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngo',
            name='pref2',
        ),
        migrations.RemoveField(
            model_name='ngo',
            name='pref3',
        ),
        migrations.AlterField(
            model_name='ngo',
            name='pref1',
            field=models.IntegerField(choices=[(0, 'Morning'), (1, 'Afternoon'), (2, 'Evening'), (3, 'Anytime')], default=None),
        ),
    ]
