# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0006_ngo_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo',
            name='about',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
